### ISSUE TITLE
Impove support if mpd server uses upnp database

### ISSUE THREAD

**Issue by n00ris** [rbackhouse/MaximumMPD#45]
Hello,
since version 0.19, you can configure the mpd server to be an dlna client [1].

To do this, you add
```
database {
    plugin "upnp"
}
```
to the /etc/mpd.conf file.

With this, you can browse you DLNA servers in your network, e.g. from a NAS with Openmediavault and MiniDLNA.

Unfortunetaly, MaximumMPD does not list all files if you browse the directories provided by the minidlna. This is working with a ncmpcpp client (installed on the same system as the mpd server)

Tested with mpd 0.20 from ubuntu 18.04

**Steps to reproduce:**
- run minidlna in your network
- configure mpd as dlna/upnp client
- connect to this mpd via MaximumMPD
- in MaximumMPD, go to files , select minidlna , select folder and navigate to a folder with more than 2 music files.

**Actual Result:**
- zero, one or two music files are listed

**Expected result:**
- all music files of the folder should be listed

Thanks

**Offtopic/Related:**
If you use Plex instead of MiniDLNA, MaximumMPD cannot list files at all. Connecting to PLEX via files just give an error.

[1]
https://www.lesbonscomptes.com/pages/mpd-upnp.html

**Comment by rbackhouse** [comment]
The problem is that the plugin return files entries with no file extensions an the App filters based on the supported types that are provided by the MPD instance. I can allow the File browser itshow these extensionless file entries and it enables the browsing.

I don't think the Plex issue is an MPD client problem. I was not able to get anything to work with Plex. I suspect its an MPD UPnP plugin issue

**Comment by rbackhouse** [comment]
This now available in Version 3.7
