### ISSUE TITLE
Albums display error

### ISSUE THREAD

**Issue by KokonZhang** [rbackhouse/MaximumMPD#55]
In setting>connections shows 202 albums, which is correct, but in browse>albums shows  302 albums. The reason is there are many singers in one album, it will display as many albums instead of one only. 
Bye the way, it will be nice if can customize how many cover arts in one row.

**Comment by rbackhouse** [comment]
Depending on your music database both the numbers of albums on the connection and on the Album browse screen can be wrong. 

If your database has Albums with multiple Artists then yes you will see them duplicated on the Albums Browse Screen. 

If your database has Albums with the same name but are totally different Albums then the number of albums on the connection summary will be wrong. This data is coming from the MPD status command and does not seem to take this into consideration.

I prefer to have the duplicates instead of have missing albums as would be the case if I remove Albums with duplicate names not taking the name of the album artist into consideration.

For the Album Art what sort of device are you using ? iPhone or iPad ?

**Comment by KokonZhang** [comment]
I am using iPhone. I also install another app named yaMPC, it works well if MPD’s version is earlier than 0.19
Kokon
发自我的iPhone

**Comment by rbackhouse** [comment]
I've opened an enhancement request for configuring the number of grid columns

https://github.com/rbackhouse/MaximumMPD/issues/57
