### ISSUE TITLE
random playlist enhancements

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#63]
Two enhancement requests for random playlists:
1. add random playlist by date e.g. 1972
2. allow multiple keywords for artist and genre playlists e.g. jazz blues, or bach mozart

Thank you for your consideration.  I use MaximumMpd all the time.

**Comment by rbackhouse** [comment]
Adding by date is straight forward. Adding multiple values for artist and genre is a little more involved. 

As the ui is using a simple text entry field figuring out what would separate the values will need some thought. 

A single value can have spaces so that's out. I could use quotes but then entering them in via a mobile device becomes a bit cumbersome. 

Perhaps using a "+" might be easier to manage.

**Comment by guestguestguestguest** [comment]
Using a '+' to delimit multiple values would be perfectly fine with me. Thanks for your consideration.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
Available in version 4.6 in the App Store.
You can use the "+" for multiple values on all types.

I also added a configuration option for specifying the Random Playlist size. It defaults to 50 but can go up to 300 via increments of 50.

**Comment by guestguestguestguest** [comment]
Sweet! Thanks much Richard!

F
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
